### ISSUE TITLE
Flair support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [tecnoscimmie/tsredditbot#2]
A configurable option to force the link to have a Flair must be in place. In our case we need this set by default to *true*.

This means, that if a user wants to post a Link MUST use one of the valid flair available in the reddit channel.

**Comment by gsora** [comment]
A command to list all the available flairs on the subreddit should be added too, otherwise users will be unaware of them.

> In our case we need this set by default to *true*.

We can deal with this kind of conditions through the configuration file.

**Comment by julianxhokaxhiu** [comment]
Sure thing, feel free to add the command you prefer in order to list them. You may return an initial list when you start to use the bot ( basically before you login ).

This may also speed up the user to actually post them.

Would also be nice that the bot does not post, if the Flair is not in the list.
